### ISSUE TITLE
Cargo dependency example incorrect

### ISSUE THREAD

**Issue by KeiranY** [Impalabs/keystone-bindings#1]
The example in README.md for adding the module to cargo is incorrect since the name of the crate is `keystone-engine` not `keystone_engine`

It should be:

```toml
keystone-engine = { version = "0.1.0", features = ["build-from-src"] }
```

**Comment by 0xLyte** [comment]
Thanks for the fix!
And sorry for the delay, I've just realized my Github notifications were not configured properly.
